name: 'OneReport Publisher'
description: 'Publish Test Results to SmartBear OneReport'
inputs:
  organization-id:
    description: 'OneReport organization id'
    required: true
  token:
    description: 'OneReport token'
    required: true
  reports:
    description: 'Globs to the files to publish'
    required: true
  max-time:
    description: 'Max time for each request'
    required: false
  ignore-error:
    description: 'Exit with 0 even if a timeout or error occurred'
    required: false
    default: 'false'
  url:
    description: 'OneReport URL'
    required: false
    default: 'https://one-report.vercel.app'
  zip:
    description: 'If true, compress all non .zip files into a zip file before publishing'
    required: false
    default: 'true'
outputs:
  report-urls:
    description: 'Report URLs'
runs:
  using: 'node16'
  main: 'action/index.cjs'
