name: 'OneReport Publisher'
description: 'Publish Test Results to SmartBear OneReport'
inputs:
  organization-id:
    description: 'OneReport organization id'
    required: true
  password:
    description: 'OneReport password'
    required: true
  reports:
    description: 'Globs to the JUnit XML/Cucumber JSON files to publish'
    required: true
  url:
    description: 'OneReport URL'
    required: false
    default: 'https://one-report.vercel.app'
outputs:
  report-urls:
    description: 'Report URLs'
runs:
  using: 'node16'
  main: 'action/index.cjs'
