name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: set git core.autocrlf to 'input'
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm test

      - name: Publish Results to OneReport
        if: ${{ always() }}
        # uses: smartbear/one-report-publisher@v1.0.0
        uses: ./
        with:
          # The organization-id cannot come from a repository secret, because
          # GitHub Actions masks all secrets from the output. We need to be able
          # to print the report URLs, which contain the organization-id.
          # This is OK - the repository-id isn't sensitive information.
          organization-id: 559fa0f2-1343-43a9-b843-90644305ee07
          password: ${{ secrets.ONE_REPORT_PASSWORD }}
          reports: tmp/tests/*.{json,xml}

      - run: npm run eslint
      - run: npm run build
