name: test-javascript

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    env:
      ONE_REPORT_TEST_ORGANIZATION_ID: ${{ secrets.ONE_REPORT_TEST_ORGANIZATION_ID }}
      ONE_REPORT_PASSWORD: ${{ secrets.ONE_REPORT_PASSWORD }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node-version: ['14.x', '16.x', '17.x']
        include:
          - os: windows-latest
            node-version: '16.x'
          - os: macos-latest
            node-version: '16.x'

    steps:
      - name: set git core.autocrlf to 'input'
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2
      - name: with Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install-test
      - name: Publish Results to OneReport
        if: ${{ always() }}
        id: one-report-publisher
        # uses: smartbear/one-report-publisher@v1.0.0
        uses: ./
        with:
          # The organization-id cannot come from a repository secret, because
          # GitHub Actions masks all secrets from the output. We need to be able
          # to print the report URLs, which contain the organization-id.
          # This is OK - the repository-id isn't sensitive information.
          organization-id: 559fa0f2-1343-43a9-b843-90644305ee07
          password: ${{ secrets.ONE_REPORT_PASSWORD }}
          reports: tmp/tests/*.{json,xml}
      - run: npm run eslint
