name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ONE_REPORT_ORGANIZATION: ${{ secrets.ONE_REPORT_ORGANIZATION_ID }}
      ONE_REPORT_URL: ${{ secrets.ONE_REPORT_URL }}
      ONE_REPORT_TOKEN: ${{ secrets.ONE_REPORT_TOKEN }}

    steps:
      - name: set git core.autocrlf to 'input'
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm test

      - name: Publish Results to OneReport (CLI)
        run: node bin/one-report-publisher.cjs --reports "tmp/tests/*.{json,xml}"
      - name: Publish Results to OneReport (GitHub Action)
        if: ${{ always() }}
        # uses: smartbear/one-report-publisher@v1.0.0
        uses: ./
        with:
          reports: tmp/tests/*.{json,xml}

      - run: npm run eslint
      - run: npm run build
