name: Run Tests

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          # - ubuntu-latest
        # 16.12.0 has broken ESM support
        node-version: ['12.x', '14.x', '16.11.x', '17.x']
        include:
          - os: windows-latest
            node-version: '17.x'
          # - os: macos-latest
          #   node-version: '17.x'
    env:
      ONE_REPORT_PROJECT_ID: ${{ secrets.ONE_REPORT_PROJECT_ID }}
      ONE_REPORT_URL: ${{ secrets.ONE_REPORT_URL }}
      ONE_REPORT_REFRESH_TOKEN: ${{ secrets.ONE_REPORT_REFRESH_TOKEN }}

    steps:
      - name: set git core.autocrlf to 'input'
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm test

      - name: Publish Results to OneReport (CLI)
        run: node bin/one-report-publisher.cjs --reports "tmp/tests/*.{json,xml}"
      - name: Publish Results to OneReport (GitHub Action)
        if: ${{ always() }}
        # uses: smartbear/one-report-publisher@v1.0.0
        uses: ./
        with:
          reports: tmp/tests/*.{json,xml}

      - run: npm run eslint
      - run: npm run build
